### ISSUE TITLE
xattrs are not preserved in final image

### ISSUE THREAD

**Issue by cyphar** [brauner/docker-melt#3]
This is a bit hard to show given #1, but if it did work, you'll end up with the following:

```
% docker run -it tumbleweed:squashed sh
sh-4.3# useradd user
sh-4.3# su user
bash-4.3$ ping -c1 127.0.0.1
ping: icmp open socket: Operation not permitted
```

If you check the `ping` binary with `getcap` you find that it doesn't have any extended attributes (which it should on an `opensuse` image).

**Comment by brauner** [comment]
This is probably due to `tar`. https://github.com/brauner/melt/commit/3e700b3cd814b8e5decac3dc9229cb9b13266104 should fix it. But I should mention that I find the xattr-handling of `tar` not working very reliably even when using `--xattrs` during tarring and untarring. With `tar 1.28` it still seems to fail to preserve xattrs.

**Comment by cyphar** [comment]
Yeah, you're right that it doesn't fix it. That's quite odd. We very recently solved [this problem in Kiwi](https://github.com/openSUSE/kiwi/pull/556) by adding `--xattrs` to the `tar` cmdline.
